network: Sepolia
safe-block-buffer: 12
evm-block-listen: true
usdc-listen: true
rpc-urls:
  - https://0xrpc.io/sep
  - https://ethereum-sepolia-rpc.publicnode.com
  - https://eth-sepolia-testnet.api.pocket.network
