network: Sepolia
native-asset: ETH
safe-block-buffer: 12
max-blocks-per-tick: 100
evm-block-listen: true
usdc-listen: true

database:
  host: # redacted
  port: # redacted
  user: # redacted
  password: # redacted
  dbname: # redacted
  sslmode: # redacted
  timezone: # redacted

rpc-urls:
  - https://0xrpc.io/sep
  - https://ethereum-sepolia-rpc.publicnode.com
  - https://eth-sepolia-testnet.api.pocket.network
