spring:
  application:
    name: ledger
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  datasource:
    url: #redacted
    username: #redacted
    password: redacted
    driver-class-name: org.postgresql.Driver

nats:
  url: #redacted
  subject: chainops.block.activity
  consumer: ledger-ops
