spring.application.name=ledger

nats.url=nats://localhost:4222
nats.subject=chainops.block.activity
nats.consumer=ledger-consumer

spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
