spring.application.name=ledger

nats.url=nats://localhost:4222
nats.subject=chainops.block.activity
nats.consumer=ledger-consumer

spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

# PostgreSQL datasource
spring.datasource.url=#redacted
spring.datasource.username=#redacted
spring.datasource.password=redacted
spring.datasource.driver-class-name=org.postgresql.Driver